name: mosquitto_broker
services:
    mosquitto:
        image: eclipse-mosquitto:latest
        container_name: mosquitto_broker
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - ./server/config:/mosquitto/config
            - ./server/data:/mosquitto/data
            - ./server/log:/mosquitto/log
        networks:
            - backend
networks:
    backend:
        name: lab_net
        driver: bridge
