syntax = "proto3";

service SensorServer {
  rpc TriggerCapturePc (TriggerRequest) returns (CaptureResponse);
  rpc AddSensor (SensorInfo) returns (EmptyResponse);
  rpc GetSensorIds (EmptyRequest) returns (AvailableSensors);
}

service SingleSensor {
    rpc TriggerCapture (TriggerRequest) returns (CaptureResponse);
}

message TriggerRequest {
    string id = 1;
}

message CaptureResponse {
    bytes image_data = 1;
}

message EmptyResponse {}

message SensorInfo {
  string id = 1;
  string ip = 2;
  int32  port = 3;
}

message EmptyRequest {}  

message AvailableSensors {
  repeated string ids = 1;  
}
