# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import proto.sensor_pb2 as sensor__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sensor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SensorServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerCapturePc = channel.unary_unary(
                '/SensorServer/TriggerCapturePc',
                request_serializer=sensor__pb2.TriggerRequest.SerializeToString,
                response_deserializer=sensor__pb2.CaptureResponse.FromString,
                _registered_method=True)
        self.AddSensor = channel.unary_unary(
                '/SensorServer/AddSensor',
                request_serializer=sensor__pb2.SensorInfo.SerializeToString,
                response_deserializer=sensor__pb2.EmptyResponse.FromString,
                _registered_method=True)


class SensorServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TriggerCapturePc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerCapturePc': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerCapturePc,
                    request_deserializer=sensor__pb2.TriggerRequest.FromString,
                    response_serializer=sensor__pb2.CaptureResponse.SerializeToString,
            ),
            'AddSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSensor,
                    request_deserializer=sensor__pb2.SensorInfo.FromString,
                    response_serializer=sensor__pb2.EmptyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SensorServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SensorServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SensorServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TriggerCapturePc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SensorServer/TriggerCapturePc',
            sensor__pb2.TriggerRequest.SerializeToString,
            sensor__pb2.CaptureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SensorServer/AddSensor',
            sensor__pb2.SensorInfo.SerializeToString,
            sensor__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SingleSensorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerCapture = channel.unary_unary(
                '/SingleSensor/TriggerCapture',
                request_serializer=sensor__pb2.TriggerRequest.SerializeToString,
                response_deserializer=sensor__pb2.CaptureResponse.FromString,
                _registered_method=True)


class SingleSensorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TriggerCapture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SingleSensorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerCapture': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerCapture,
                    request_deserializer=sensor__pb2.TriggerRequest.FromString,
                    response_serializer=sensor__pb2.CaptureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SingleSensor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SingleSensor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SingleSensor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TriggerCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SingleSensor/TriggerCapture',
            sensor__pb2.TriggerRequest.SerializeToString,
            sensor__pb2.CaptureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
