# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\"\x1c\n\x0eTriggerRequest\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\x0f\x43\x61ptureResponse\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"\x0f\n\rEmptyResponse\"2\n\nSensorInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x32o\n\x0cSensorServer\x12\x35\n\x10TriggerCapturePc\x12\x0f.TriggerRequest\x1a\x10.CaptureResponse\x12(\n\tAddSensor\x12\x0b.SensorInfo\x1a\x0e.EmptyResponse2C\n\x0cSingleSensor\x12\x33\n\x0eTriggerCapture\x12\x0f.TriggerRequest\x1a\x10.CaptureResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRIGGERREQUEST']._serialized_start=16
  _globals['_TRIGGERREQUEST']._serialized_end=44
  _globals['_CAPTURERESPONSE']._serialized_start=46
  _globals['_CAPTURERESPONSE']._serialized_end=83
  _globals['_EMPTYRESPONSE']._serialized_start=85
  _globals['_EMPTYRESPONSE']._serialized_end=100
  _globals['_SENSORINFO']._serialized_start=102
  _globals['_SENSORINFO']._serialized_end=152
  _globals['_SENSORSERVER']._serialized_start=154
  _globals['_SENSORSERVER']._serialized_end=265
  _globals['_SINGLESENSOR']._serialized_start=267
  _globals['_SINGLESENSOR']._serialized_end=334
# @@protoc_insertion_point(module_scope)
